
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipologiasEmpresa](
	[IdEmpresa] [int] NOT NULL,
	[IdTipologia] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TipologiasEmpresa] ADD  CONSTRAINT [PK_TipologiasEmpresa] PRIMARY KEY CLUSTERED 
(
	[IdTipologia] ASC,
	[IdEmpresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TipologiasEmpresa_IdEmpresa] ON [dbo].[TipologiasEmpresa]
(
	[IdEmpresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TipologiasEmpresa]  WITH CHECK ADD  CONSTRAINT [FK_TipologiasEmpresa_Empresa_IdEmpresa] FOREIGN KEY([IdEmpresa])
REFERENCES [dbo].[Empresa] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TipologiasEmpresa] CHECK CONSTRAINT [FK_TipologiasEmpresa_Empresa_IdEmpresa]
GO
ALTER TABLE [dbo].[TipologiasEmpresa]  WITH CHECK ADD  CONSTRAINT [FK_TipologiasEmpresa_Tipologia_IdTipologia] FOREIGN KEY([IdTipologia])
REFERENCES [dbo].[Tipologia] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TipologiasEmpresa] CHECK CONSTRAINT [FK_TipologiasEmpresa_Tipologia_IdTipologia]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipologia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](75) NOT NULL,
	[Active] [bit] NOT NULL,
	[NameEnglish] [nvarchar](75) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [PK_Tipologia] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [DF_Tipologia_Name]  DEFAULT ('') FOR [Name]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [DF_Tipologia_NameEnglish]  DEFAULT ('') FOR [NameEnglish]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipologia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](75) NOT NULL,
	[Active] [bit] NOT NULL,
	[NameEnglish] [nvarchar](75) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [PK_Tipologia] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [DF_Tipologia_Name]  DEFAULT ('') FOR [Name]
GO
ALTER TABLE [dbo].[Tipologia] ADD  CONSTRAINT [DF_Tipologia_NameEnglish]  DEFAULT ('') FOR [NameEnglish]
GO

